[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_movie_review_program = "7qqKMfVAqhNZecAAVmWagnWZ7MzAWFiwtVaX3YZ5vBdB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/lxsh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
